Configurable env path from ngxEnv options
chihab/ngx-env pull request #42
Opened 2023-05-27 07:50 UTC by otonielguajardo

dotenv supports specifying the path of the .env file, this PR tries to acomplish the same.

It would be awesome for proyects with structures like this:
![Screenshot 2023-05-27 at 1 46 21 a m](https://github.com/chihab/ngx-env/assets/23427095/e9da81e4-f1af-48e3-90e0-17c565bf131b)

2023-05-28 13:58 UTC, chihab commented
Hey, very good idea. 
The only potential confustion is that we specify the .env file but we might have other files like .env.dev or .env.local that are also parsed when present.
I wonder if it wouldn't be better to set path as the folder containing the .env files rather than the file itself. WDYT?

```
            "ngxEnv": {
              "prefix": "NGX_",
              "path": ".." // could be relative or absolute
            },
```

There also another use case in monorepo setup on which we'd want have a root .env file and each project in the workspace might have their .env files that override the properties from the parent.
```
cvnl-map
  apps/
      frontend1
          .env
       frontend2
          .env
.env
```

In that case the `base` config of frontend1 and frontend2 would target the root .env
```
            "ngxEnv": {
              "prefix": "NGX_",
              "path": "../../" 
            },
```
and we should load all the .env files from the root to the project one, the latter can override keys from the former.

2023-05-28 18:17 UTC, chihab commented
could you add the option to the ngx-env.json file?

```
"path": {
    "type": "string",
    "description": "@ngx-env/builder path to .env file",
    "default": ".env"
}
```

2023-05-28 18:18 UTC, chihab requested changes

2023-05-28 18:18 UTC, chihab commented on packages/builder/src/builders/plugin.ts
> +function getClientEnvironment(prefix: RegExp, envPath: string = ".env") {
by adding a default value to ngxEnv builder options (previous comment), the default value here is not needed

2023-05-28 20:08 UTC, otonielguajardo commented
> could you add the option to the ngx-env.json file?
> 
> ```
> "path": {
>     "type": "string",
>     "description": "@ngx-env/builder path to .env file",
>     "default": ".env"
> }
> ```

Sure thing! I've updated the PR

2023-05-28 22:17 UTC, chihab approved these changes

2023-05-28 22:46 UTC, merged

2023-05-29 05:21 UTC, chihab commented
Thank you @otonielguajardo!